version: '3.1'

services:
  mongo:
    image: mongo:3.6
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - db-data:/data/db

  mongo-express:
    image: mongo-express:0.49
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
    depends_on:
      - mongo
  
  metal-api:
    build: ./
    command: sh start.sh
    volumes:
      - "./:/usr/src/metal-api"
    ports:
      - 9080:9080
    depends_on:
      - mongo

volumes:
  db-data:
